CREATE TABLE "public"."CODIGO_MUNICIPIO" (
	"ID_COD_MUNICIPIO" Serial PRIMARY KEY, 
	"COD_MUNICIPIO" Double Precision NOT NULL, 
	"UF" Varchar(2) NOT NULL, 
	"NOME" Varchar(255) NOT NULL, 
	"NOME_SEM_ACENTO" Varchar(255)
)
GO
CREATE UNIQUE INDEX "Idx_COD_MUNICIPIO" ON "CODIGO_MUNICIPIO"
	 USING btree ("COD_MUNICIPIO")
GO

CREATE TABLE "public"."EMPRESA" (
	"ID_EMPRESA" Serial PRIMARY KEY, 
	"CODIGO_EXTERNO" Integer, 
	"RAZAO_SOCIAL" Varchar(50), 
	"NOME_FANTASIA" Varchar(50), 
	"CNPJ" Varchar(14), 
	"INSCRICAO_ESTADUAL" Varchar(20), 
	"CODIGO_MUNICIPIO" Integer, 
	"ENDERECO" Varchar(50), 
	"NUMERO" Integer, 
	"COMPLEMENTO" Varchar(30), 
	"BAIRRO" Varchar(30), 
	"CEP" Varchar(10), 
	"TELEFONE" Varchar(20), 
	"EMAIL" Varchar(30), 
	"DIA_FECHAMENTO" Integer, 
	"ID_ESTADO" Integer
)
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49262
	 
	ON EMPRESA
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49263
	 
	ON EMPRESA
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49348
	 
	ON EMPRESA
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49349
	 
	ON EMPRESA
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_65842
	 
	ON EMPRESA
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_65843
	 
	ON EMPRESA
	FOR EACH
GO

CREATE TABLE "public"."EMPRESA_PARAMETROS" (
	"ID_PARAMETROS_EMPRESA" Serial PRIMARY KEY, 
	"ID_EMPRESA" Integer, 
	"PERIODO" timestamp, 
	"TURNOS" Integer, 
	"PAGAMENTO_HE_ANTES_HORARIO" Boolean DEFAULT false, 
	"PAGAMENTO_HE_DEPOIS_HORARIO" Boolean DEFAULT false, 
	"TOLERANCIA_HORAEXTRA" Integer, 
	"TOLERANCIA_ATRASO" Integer, 
	"INICIO_EXPEDIENTE" time, 
	"HORAS_BONIFICACAO" time, 
	"PORC_HORAS_BONIFICACAO" Integer, 
	"PORC_BONIFICACAO_FERIADO_FOLGA" Integer, 
	"PORC_BONIFICACAO_DEMAIS_HORAS" Integer, 
	"HORA_INICIO_ADICIONALNOTURNO" Integer, 
	"HORA_FIM_ADICIONALNOTURNO" Integer, 
	"DESCONTO_INTERVALO_NOTURNO" Boolean DEFAULT false, 
	"TRABALHA_BANCOHORAS" Boolean DEFAULT false, 
	"ALMOCO_FLEXIVEL" Boolean DEFAULT false, 
	"ENTRADA_SAIDA_FLEXIVEL" Boolean DEFAULT false, 
	FOREIGN KEY ("ID_EMPRESA")
		REFERENCES "public"."EMPRESA" ("ID_EMPRESA")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_65844
	 
	ON EMPRESA_PARAMETROS
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_65845
	 
	ON EMPRESA_PARAMETROS
	FOR EACH
GO

CREATE TABLE "public"."ESTADOS" (
	"ID_ESTADO" Serial PRIMARY KEY, 
	"UF" Varchar(2), 
	"NOME" Varchar(50)
)
GO

CREATE TABLE "public"."FERIADO" (
	"ID_FERIADO" Serial PRIMARY KEY, 
	"CODIGO_EXTERNO" Integer, 
	"DATA_FERIADO" timestamp, 
	"DESCRICAO" Varchar(50), 
	"ABRANGENCIA" Integer, 
	"CODIGO_MUNICIPIO" Integer
)
GO

CREATE TABLE "public"."FUNCIONARIO" (
	"ID_FUNCIONARIO" Serial PRIMARY KEY, 
	"CODIGO_EXTERNO" Integer, 
	"NOME" Varchar(50), 
	"DATA_NASCIMENTO" timestamp, 
	"SALARIO" Double Precision, 
	"ID_EMPRESA" Integer, 
	"PIS" Varchar(20), 
	"RG" Varchar(10), 
	"CTPS" Varchar(30), 
	"DATA_ADMISSAO" timestamp, 
	"DATA_DEMISSAO" timestamp, 
	"CPF" Varchar(14), 
	"CONFIGURACAO_INDIVIDUAL" Boolean DEFAULT false, 
	FOREIGN KEY ("ID_EMPRESA")
		REFERENCES "public"."EMPRESA" ("ID_EMPRESA")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49264
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49265
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49275
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49276
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49288
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49289
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49343
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49344
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49412
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49413
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_57623
	 
	ON FUNCIONARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_57624
	 
	ON FUNCIONARIO
	FOR EACH
GO

CREATE TABLE "public"."FUNCIONARIO_DADOS_COMPLEMENTAR" (
	"ID_FUNCIONARIO_DADOS_C" Serial PRIMARY KEY, 
	"ID_FUNCIONARIO" Integer, 
	"ID_HORARIO" Integer, 
	"ID_TIPO_JORNADA" Integer, 
	"ID_JORNADA" Integer, 
	"INICIO_EXPEDIENTE" time, 
	"HORAS_FIXAS" Boolean DEFAULT false, 
	"QUANTIDADE_HORAS_FIXAS" Integer, 
	"ID_DIGITAIS" Integer, 
	FOREIGN KEY ("ID_FUNCIONARIO")
		REFERENCES "public"."FUNCIONARIO" ("ID_FUNCIONARIO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49290
	 
	ON FUNCIONARIO_DADOS_COMPLEMENTAR
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49291
	 
	ON FUNCIONARIO_DADOS_COMPLEMENTAR
	FOR EACH
GO

CREATE TABLE "public"."FUNCIONARIO_DADOS_PESSOAIS" (
	"ID_FUNCIONARIO_DADOS_P" Serial PRIMARY KEY, 
	"ID_FUNCIONARIO" Integer, 
	"ENDERECO" Varchar(50), 
	"NUMERO" Integer, 
	"COMPLEMENTO" Varchar(20), 
	"BAIRRO" Varchar(30), 
	"CEP" Varchar(10), 
	"CODIGO_MUNICIPIO" Integer, 
	"TELEFONE" Varchar(20), 
	"CELULAR" Varchar(20), 
	"ID_ESTADO" Integer
	FOREIGN KEY ("ID_FUNCIONARIO")
		REFERENCES "public"."FUNCIONARIO" ("ID_FUNCIONARIO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49277
	 
	ON FUNCIONARIO_DADOS_PESSOAIS
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49278
	 
	ON FUNCIONARIO_DADOS_PESSOAIS
	FOR EACH
GO

CREATE TABLE "public"."FUNCIONARIO_OBSERVACAO" (
	"ID_FUNCIONARIO_OBSERVACAO" Serial PRIMARY KEY, 
	"ID_FUNCIONARIO" Integer, 
	"NOME_EXIBICAO" Varchar(50), 
	"SENHA_RELOGIO" Varchar(50), 
	FOREIGN KEY ("ID_FUNCIONARIO")
		REFERENCES "public"."FUNCIONARIO" ("ID_FUNCIONARIO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49414
	 
	ON FUNCIONARIO_OBSERVACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49415
	 
	ON FUNCIONARIO_OBSERVACAO
	FOR EACH
GO

CREATE TABLE "public"."FUNCIONARIO_PARAMETROS" (
	"ID_FUNCIONARIO_PARAMETROS" Serial PRIMARY KEY, 
	"ID_FUNCIONARIO" Integer, 
	"PERIODO" timestamp, 
	"TURNOS" Integer, 
	"PAGTO_HE_ANTES_HORARIO" Boolean DEFAULT false, 
	"PAGTO_HE_DEPOIS_HORARIO" Boolean DEFAULT false, 
	"TOLERANCIA_HORAEXTRA" Integer, 
	"TOLERANCIA_ATRASO" Integer, 
	"INICIO_EXPEDIENTE" time, 
	"HORAS_BONIFICACAO" time, 
	"PORC_HORAS_BONIFICACAO" Integer, 
	"PORCENTAGEM_FERIADO_FOLGA" Integer, 
	"PORCENTAGEM_DEMAIS_HORAS" Integer, 
	"HORA_INICIO_ADICIONALNOTURNO" Integer, 
	"HORA_FIM_ADICIONALNOTURNO" Integer, 
	"DESC_INTERVALO_NOTURNO" Boolean DEFAULT false, 
	"TRABALHA_BANCOHORAS" Boolean DEFAULT false, 
	"ALMOCO_FLEXIVEL" Boolean DEFAULT false, 
	"ENT_SAI_FLEXIVEL" Boolean DEFAULT false, 
	FOREIGN KEY ("ID_FUNCIONARIO")
		REFERENCES "public"."FUNCIONARIO" ("ID_FUNCIONARIO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_57625
	 
	ON FUNCIONARIO_PARAMETROS
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_57626
	 
	ON FUNCIONARIO_PARAMETROS
	FOR EACH
GO

CREATE TABLE "public"."HORARIO" (
	"ID_HORARIO" Serial PRIMARY KEY, 
	"CODIGO_EXTERNO" Integer NOT NULL, 
	"DESCRICAO" Varchar(50), 
	"POSSUI_ESCALA" Boolean DEFAULT false
)
GO
CREATE TRIGGER RI_ConstraintTrigger_a_40998
	 
	ON HORARIO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_40999
	 
	ON HORARIO
	FOR EACH
GO

CREATE TABLE "public"."HORARIO_DETALHE" (
	"ID_HORARIO_DETALHE" Serial PRIMARY KEY, 
	"ID_HORARIO" Integer NOT NULL, 
	"ENTRADA" time, 
	"ALMOCO_INICIO" time, 
	"ALMOCO_FIM" time, 
	"SAIDA" time, 
	"DIA_SEMANA" Integer, 
	"HORAS_A_TRABALHAR" time, 
	FOREIGN KEY ("ID_HORARIO")
		REFERENCES "public"."HORARIO" ("ID_HORARIO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_41000
	 
	ON HORARIO_DETALHE
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_41001
	 
	ON HORARIO_DETALHE
	FOR EACH
GO

CREATE TABLE "public"."MOVIMENTACAO" (
	"ID_MOVIMENTACAO" Serial PRIMARY KEY, 
	"ID_FUNCIONARIO" Integer NOT NULL, 
	"ID_EMPRESA" Integer NOT NULL, 
	FOREIGN KEY ("ID_FUNCIONARIO")
		REFERENCES "public"."FUNCIONARIO" ("ID_FUNCIONARIO")
		ON UPDATE CASCADE ON DELETE CASCADE, 
	FOREIGN KEY ("ID_EMPRESA")
		REFERENCES "public"."EMPRESA" ("ID_EMPRESA")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49345
	 
	ON MOVIMENTACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49346
	 
	ON MOVIMENTACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49350
	 
	ON MOVIMENTACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49351
	 
	ON MOVIMENTACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49362
	 
	ON MOVIMENTACAO
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_a_49363
	 
	ON MOVIMENTACAO
	FOR EACH
GO

CREATE TABLE "public"."MOVIMENTACAO_DETALHE" (
	"ID_MOVIMENTACAO_DETALHE" Serial PRIMARY KEY, 
	"ID_MOVIMENTACAO" Integer NOT NULL, 
	"DATA_HORA_MOVIMENTACAO" timestamp NOT NULL, 
	FOREIGN KEY ("ID_MOVIMENTACAO")
		REFERENCES "public"."MOVIMENTACAO" ("ID_MOVIMENTACAO")
		ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49364
	 
	ON MOVIMENTACAO_DETALHE
	FOR EACH
GO
CREATE TRIGGER RI_ConstraintTrigger_c_49365
	 
	ON MOVIMENTACAO_DETALHE
	FOR EACH
GO

CREATE TABLE "public"."USUARIOS" (
	"ID_LOGIN" Serial PRIMARY KEY, 
	"USUARIO" Varchar(30), 
	"SENHA" Varchar(255)
)
GO
